const qs=(s,r=document)=>r.querySelector(s);const qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const coarsePointer=matchMedia('(pointer: coarse)').matches;
const polishPreload=qs('[data-polish-preload]');function activatePolish(){if(!polishPreload||polishPreload.rel==='stylesheet')return;polishPreload.rel='stylesheet';polishPreload.removeAttribute('as')}if(polishPreload){requestAnimationFrame(()=>requestAnimationFrame(activatePolish))}

const toast=qs('[data-toast]');let toastTimer;function showToast(message){if(!toast)return;toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2400)}

const intro=qs('[data-intro]');const enterButton=qs('[data-enter]');const shell=[...qsa('[data-shell]'),qs('.skip-link')].filter(Boolean);function lockShell(locked){for(const el of shell){if(locked)el.setAttribute('inert','');else el.removeAttribute('inert')}}function enterExperience(){if(!intro||intro.classList.contains('is-leaving'))return;activatePolish();intro.classList.add('is-leaving');lockShell(false);setTimeout(()=>intro.remove(),reduceMotion?0:650);const top=qs('#top');if(top){top.tabIndex=-1;top.focus({preventScroll:true})}launchCelebration()}
if(intro&&enterButton){lockShell(true);requestAnimationFrame(()=>enterButton.focus({preventScroll:true}));enterButton.addEventListener('click',enterExperience);intro.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target===intro)enterExperience()})}

const revealItems=qsa('.reveal');if(!('IntersectionObserver'in window)||reduceMotion){revealItems.forEach(el=>el.classList.add('visible'))}else{const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}},{threshold:.12,rootMargin:'0px 0px -6%'});revealItems.forEach(el=>observer.observe(el))}

const countdown=qs('[data-countdown]');let countdownTimer;if(countdown){const target=new Date(countdown.dataset.date).getTime();const paint=()=>{const delta=Math.max(0,target-Date.now());const parts=[Math.floor(delta/86400000),Math.floor(delta%86400000/3600000),Math.floor(delta%3600000/60000),Math.floor(delta%60000/1000)];['[data-days]','[data-hours]','[data-minutes]','[data-seconds]'].forEach((selector,i)=>{const node=qs(selector,countdown);if(node)node.textContent=String(parts[i]).padStart(2,'0')})};paint();countdownTimer=setInterval(paint,1000)}

const events={henna:{title:'ليلة حنة MOHAMED × A',date:'2026-09-03',location:'',description:'GARHY Invite — Festival Edition'},wedding:{title:'ليلة زفاف MOHAMED × A',date:'2026-09-04',location:'قاعة شهرزاد — سنورس — الفيوم',description:'GARHY Invite — Festival Edition'}};
function ymd(date){return date.toISOString().slice(0,10).replaceAll('-','')}function downloadIcs(key){const event=events[key];if(!event)return;const start=new Date(`${event.date}T12:00:00Z`);const end=new Date(start);end.setUTCDate(end.getUTCDate()+1);const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//GARHY TECH//GARHY Invite//AR','CALSCALE:GREGORIAN','METHOD:PUBLISH','BEGIN:VEVENT',`UID:${key}-mohamed-a-2026@garhy.ai`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;VALUE=DATE:${ymd(start)}`,`DTEND;VALUE=DATE:${ymd(end)}`,`SUMMARY:${event.title}`,`DESCRIPTION:${event.description}`,`LOCATION:${event.location}`,'END:VEVENT','END:VCALENDAR'];const blob=new Blob([lines.join('\r\n')],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`mohamed-a-${key}-2026.ics`;a.rel='noopener';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),800);showToast('تم تجهيز التاريخ للتقويم')}
qsa('[data-calendar]').forEach(btn=>btn.addEventListener('click',()=>downloadIcs(btn.dataset.calendar)));

async function copyInvite(){try{await navigator.clipboard.writeText(location.href);showToast('تم نسخ رابط الدعوة')}catch{const input=document.createElement('textarea');input.value=location.href;input.setAttribute('readonly','');input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();document.execCommand('copy');input.remove();showToast('تم نسخ رابط الدعوة')}}
async function shareInvite(){const data={title:'MOHAMED × A — GARHY Invite',text:'ليلة الحنة 03/09/2026 • ليلة الزفاف 04/09/2026',url:location.href};try{if(navigator.share)await navigator.share(data);else await copyInvite()}catch(err){if(err?.name!=='AbortError')await copyInvite()}}
qsa('[data-share]').forEach(btn=>btn.addEventListener('click',shareInvite));

if(!coarsePointer&&!reduceMotion){qsa('[data-tilt]').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1000px) rotateX(${(-y*3.2).toFixed(2)}deg) rotateY(${(x*4.2).toFixed(2)}deg) translateY(-3px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});const hero=qs('.hero');hero?.addEventListener('pointermove',e=>{const x=(e.clientX/innerWidth-.5)*2;const y=(e.clientY/innerHeight-.5)*2;hero.style.setProperty('--mx',x.toFixed(3));hero.style.setProperty('--my',y.toFixed(3))},{passive:true})}

const canvas=qs('#sparks');let ctx=null,width=0,height=0,dpr=1,ambient=[],bursts=[],raf=0,canvasRunning=false,canvasActivated=false;function makeAmbient(){const count=Math.min(coarsePointer?30:46,Math.max(20,Math.floor(width/28)));ambient=Array.from({length:count},()=>({x:Math.random()*width,y:Math.random()*height,r:Math.random()*1.4+.35,vx:(Math.random()-.5)*.22,vy:-Math.random()*.55-.12,a:Math.random()*.35+.08,h:Math.random()>.55?18:352}))}function resizeCanvas(){if(!canvas||!ctx)return;dpr=Math.min(devicePixelRatio||1,1.6);width=innerWidth;height=innerHeight;canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);makeAmbient()}function addBurst(x,y,power=1){if(reduceMotion||!ctx)return;const count=Math.round((coarsePointer?22:34)*power);const hue=Math.random()>.48?14:350;for(let i=0;i<count;i++){const angle=Math.PI*2*(i/count)+Math.random()*.08;const speed=(1.2+Math.random()*2.2)*power;bursts.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,r:.7+Math.random()*1.1,a:.85,life:0,max:38+Math.random()*24,h:hue+Math.random()*14})}}function drawCanvas(){if(!canvasRunning||!ctx)return;ctx.clearRect(0,0,width,height);for(const p of ambient){p.x+=p.vx;p.y+=p.vy;if(p.y<-10){p.y=height+10;p.x=Math.random()*width}ctx.beginPath();ctx.fillStyle=`hsla(${p.h},98%,62%,${p.a})`;ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}bursts=bursts.filter(p=>{p.life++;p.x+=p.vx;p.y+=p.vy;p.vy+=.025;p.vx*=.992;p.a=1-p.life/p.max;if(p.a<=0)return false;ctx.beginPath();ctx.fillStyle=`hsla(${p.h},100%,64%,${Math.max(0,p.a)})`;ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();return true});raf=requestAnimationFrame(drawCanvas)}function startCanvas(){if(!canvas||reduceMotion||canvasRunning)return;ctx??=canvas.getContext('2d',{alpha:true});if(!ctx)return;canvasRunning=true;resizeCanvas();drawCanvas()}function stopCanvas(){canvasRunning=false;cancelAnimationFrame(raf)}function launchCelebration(){if(reduceMotion)return;canvasActivated=true;startCanvas();setTimeout(()=>addBurst(width*.22,height*.32,1.05),120);setTimeout(()=>addBurst(width*.78,height*.27,1.15),300);setTimeout(()=>addBurst(width*.5,height*.2,.8),520)}if(canvas&&!reduceMotion){addEventListener('resize',()=>{if(canvasRunning)resizeCanvas()},{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCanvas();else if(canvasActivated)startCanvas()})}

let audioCtx=null,beatTimer=null,beatOn=false,beatReset=0;const beatButton=qs('[data-beat-toggle]');function pulse(context,time,freq,decay=.1,gain=.03){const osc=context.createOscillator();const amp=context.createGain();osc.type='sine';osc.frequency.setValueAtTime(freq,time);osc.frequency.exponentialRampToValueAtTime(Math.max(42,freq*.36),time+decay);amp.gain.setValueAtTime(gain,time);amp.gain.exponentialRampToValueAtTime(.0001,time+decay);osc.connect(amp).connect(context.destination);osc.start(time);osc.stop(time+decay)}function visualBeat(strong=false){document.body.classList.add('beat-hit');clearTimeout(beatReset);beatReset=setTimeout(()=>document.body.classList.remove('beat-hit'),strong?105:75);if(strong&&ctx)addBurst(width*(.25+Math.random()*.5),height*(.18+Math.random()*.18),.52)}function scheduleBeat(){if(!audioCtx||!beatOn)return;const t=audioCtx.currentTime+.018;pulse(audioCtx,t,108,.13,.028);pulse(audioCtx,t+.22,238,.05,.009);pulse(audioCtx,t+.48,116,.12,.024);pulse(audioCtx,t+.72,275,.045,.008);visualBeat(true);setTimeout(()=>visualBeat(false),470)}function stopBeat(){beatOn=false;clearInterval(beatTimer);beatTimer=null;beatButton?.setAttribute('aria-pressed','false');beatButton?.setAttribute('aria-label','تشغيل الإيقاع الاحتفالي');const label=qs('[data-sound-label]',beatButton);if(label)label.textContent='BEAT OFF'}beatButton?.addEventListener('click',async()=>{if(beatOn){stopBeat();return}audioCtx??=new (window.AudioContext||window.webkitAudioContext)();await audioCtx.resume();beatOn=true;beatButton.setAttribute('aria-pressed','true');beatButton.setAttribute('aria-label','إيقاف الإيقاع الاحتفالي');const label=qs('[data-sound-label]',beatButton);if(label)label.textContent='BEAT ON';scheduleBeat();beatTimer=setInterval(scheduleBeat,960)});

addEventListener('pagehide',()=>{clearInterval(countdownTimer);stopBeat();stopCanvas()});
