const qs=(s,r=document)=>r.querySelector(s);const qsa=(s,r=document)=>[...r.querySelectorAll(s)];

const revealObserver=new IntersectionObserver((entries)=>{for(const e of entries){if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}},{threshold:.14});qsa('.reveal').forEach(el=>revealObserver.observe(el));

const countdown=qs('[data-countdown]');if(countdown){const target=new Date(countdown.dataset.date).getTime();const update=()=>{const now=Date.now();const delta=Math.max(0,target-now);const d=Math.floor(delta/86400000);const h=Math.floor(delta%86400000/3600000);const m=Math.floor(delta%3600000/60000);const s=Math.floor(delta%60000/1000);qs('[data-days]',countdown).textContent=String(d).padStart(2,'0');qs('[data-hours]',countdown).textContent=String(h).padStart(2,'0');qs('[data-minutes]',countdown).textContent=String(m).padStart(2,'0');qs('[data-seconds]',countdown).textContent=String(s).padStart(2,'0')};update();setInterval(update,1000)}

const toast=qs('[data-toast]');let toastTimer;function showToast(message){if(!toast)return;toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}

const events={henna:{title:'ليلة حنة MOHAMED × A',date:'20260903',location:'يتم تحديد المكان لاحقًا',description:'GARHY Invite — Festival Edition'},wedding:{title:'ليلة زفاف MOHAMED × A',date:'20260904',location:'قاعة شهرزاد — سنورس — الفيوم',description:'GARHY Invite — Festival Edition'}};
function downloadIcs(key){const event=events[key];if(!event)return;const nextDate=String(Number(event.date)+1);const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//GARHY TECH//GARHY Invite//AR','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:${key}-mohamed-a-2026@garhy.ai`,`DTSTART;VALUE=DATE:${event.date}`,`DTEND;VALUE=DATE:${nextDate}`,`SUMMARY:${event.title}`,`DESCRIPTION:${event.description}`,`LOCATION:${event.location}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([ics],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`mohamed-a-${key}-2026.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);showToast('تم تجهيز الموعد للتقويم')}
qsa('[data-calendar]').forEach(btn=>btn.addEventListener('click',()=>downloadIcs(btn.dataset.calendar)));

qs('[data-share]')?.addEventListener('click',async()=>{const data={title:'MOHAMED × A — GARHY Invite',text:'ليلة الحنة 03/09/2026 • ليلة الزفاف 04/09/2026',url:location.href};try{if(navigator.share){await navigator.share(data)}else{await navigator.clipboard.writeText(location.href);showToast('تم نسخ رابط الدعوة')}}catch(err){if(err?.name!=='AbortError')showToast('تعذر فتح المشاركة الآن')}});

qsa('[data-tilt]').forEach(card=>{card.addEventListener('pointermove',e=>{if(matchMedia('(pointer:coarse)').matches)return;const r=card.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateX(${(-y*3).toFixed(2)}deg) rotateY(${(x*4).toFixed(2)}deg) translateY(-2px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});

const canvas=qs('#sparks');const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;if(canvas&&!reduce){const ctx=canvas.getContext('2d',{alpha:true});let width,height,dpr,particles=[];function resize(){dpr=Math.min(devicePixelRatio||1,2);width=innerWidth;height=innerHeight;canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);particles=Array.from({length:Math.min(58,Math.max(26,Math.floor(width/26)))},()=>({x:Math.random()*width,y:Math.random()*height,r:Math.random()*1.5+.4,vx:(Math.random()-.5)*.25,vy:-Math.random()*.65-.15,a:Math.random()*.45+.08,h:Math.random()>.5?18:350}))}function frame(){ctx.clearRect(0,0,width,height);for(const p of particles){p.x+=p.vx;p.y+=p.vy;if(p.y<-12){p.y=height+12;p.x=Math.random()*width}ctx.beginPath();ctx.fillStyle=`hsla(${p.h},95%,58%,${p.a})`;ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(frame)}addEventListener('resize',resize,{passive:true});resize();frame()}

let audioCtx=null,beatTimer=null,beatOn=false;const beatButton=qs('[data-beat-toggle]');function pulse(ctx,time,freq,decay=.09,gain=.035){const osc=ctx.createOscillator();const amp=ctx.createGain();osc.frequency.setValueAtTime(freq,time);osc.frequency.exponentialRampToValueAtTime(Math.max(40,freq*.38),time+decay);amp.gain.setValueAtTime(gain,time);amp.gain.exponentialRampToValueAtTime(.0001,time+decay);osc.connect(amp).connect(ctx.destination);osc.start(time);osc.stop(time+decay)}function scheduleBeat(){if(!audioCtx||!beatOn)return;const t=audioCtx.currentTime+.02;pulse(audioCtx,t,120,.12,.028);pulse(audioCtx,t+.24,220,.055,.012);pulse(audioCtx,t+.48,120,.12,.025);pulse(audioCtx,t+.72,260,.05,.011)}beatButton?.addEventListener('click',async()=>{beatOn=!beatOn;beatButton.setAttribute('aria-pressed',String(beatOn));qs('[data-sound-label]',beatButton).textContent=beatOn?'BEAT ON':'BEAT OFF';if(beatOn){audioCtx??=new (window.AudioContext||window.webkitAudioContext)();await audioCtx.resume();scheduleBeat();beatTimer=setInterval(scheduleBeat,960)}else{clearInterval(beatTimer);beatTimer=null}});
