create extension if not exists pgcrypto;

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  event_type text not null check (event_type in ('wedding','engagement','birthday','conference','grand_opening','graduation','vip','corporate','other')),
  title text not null,
  subtitle text,
  timezone text not null default 'Africa/Cairo',
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  rsvp_opens_at timestamptz,
  rsvp_closes_at timestamptz,
  status text not null default 'published' check (status in ('draft','published','cancelled','archived')),
  locale_default text not null default 'ar' check (locale_default in ('ar','en')),
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table if not exists public.guests (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 120),
  phone text,
  email text,
  locale text not null default 'ar' check (locale in ('ar','en')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.invitations (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  guest_id uuid references public.guests(id) on delete set null,
  token_hash text not null unique,
  max_guests smallint not null default 1 check (max_guests between 1 and 20),
  status text not null default 'active' check (status in ('active','revoked','expired')),
  expires_at timestamptz,
  first_opened_at timestamptz,
  last_opened_at timestamptz,
  open_count integer not null default 0 check (open_count >= 0),
  created_at timestamptz not null default now()
);

create index if not exists invitations_event_idx on public.invitations(event_id);
create index if not exists invitations_guest_idx on public.invitations(guest_id);

create table if not exists public.rsvps (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  invitation_id uuid not null references public.invitations(id) on delete cascade,
  attendance text not null check (attendance in ('attending','declining')),
  guest_count smallint not null default 1 check (guest_count between 1 and 20),
  message text check (message is null or char_length(message) <= 1000),
  locale text not null default 'ar' check (locale in ('ar','en')),
  responded_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (invitation_id)
);

create index if not exists rsvps_event_idx on public.rsvps(event_id);

create table if not exists public.guest_passes (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  invitation_id uuid not null references public.invitations(id) on delete cascade,
  pass_hash text not null unique,
  pass_hint text not null,
  status text not null default 'active' check (status in ('active','revoked','used','expired')),
  issued_at timestamptz not null default now(),
  used_at timestamptz,
  revoked_at timestamptz
);

create index if not exists guest_passes_event_idx on public.guest_passes(event_id);
create index if not exists guest_passes_invitation_idx on public.guest_passes(invitation_id);

create table if not exists public.event_analytics (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  invitation_id uuid references public.invitations(id) on delete set null,
  event_name text not null check (event_name in ('invite_open','rsvp_submit','share','map_open','calendar_add','language_change','pass_issue')),
  locale text check (locale is null or locale in ('ar','en')),
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists event_analytics_event_created_idx on public.event_analytics(event_id, created_at desc);

alter table public.events enable row level security;
alter table public.guests enable row level security;
alter table public.invitations enable row level security;
alter table public.rsvps enable row level security;
alter table public.guest_passes enable row level security;
alter table public.event_analytics enable row level security;

revoke all on public.events, public.guests, public.invitations, public.rsvps, public.guest_passes, public.event_analytics from anon, authenticated;

create or replace function public.touch_updated_at()
returns trigger language plpgsql set search_path=public,pg_temp as $$
begin new.updated_at=now(); return new; end; $$;

drop trigger if exists events_touch_updated_at on public.events;
create trigger events_touch_updated_at before update on public.events for each row execute function public.touch_updated_at();
drop trigger if exists rsvps_touch_updated_at on public.rsvps;
create trigger rsvps_touch_updated_at before update on public.rsvps for each row execute function public.touch_updated_at();

create or replace function public.get_public_event(p_slug text)
returns jsonb language sql stable security definer set search_path=public,pg_temp as $$
  select jsonb_build_object(
    'slug',e.slug,'type',e.event_type,'title',e.title,'subtitle',e.subtitle,'timezone',e.timezone,
    'startsAt',e.starts_at,'endsAt',e.ends_at,'rsvpOpensAt',e.rsvp_opens_at,'rsvpClosesAt',e.rsvp_closes_at,
    'localeDefault',e.locale_default,'config',e.config)
  from public.events e where e.slug=p_slug and e.status='published' limit 1;
$$;

create or replace function public.resolve_invitation(p_token text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_inv public.invitations%rowtype; v_event public.events%rowtype; v_guest public.guests%rowtype; v_rsvp public.rsvps%rowtype;
begin
  if p_token is null or char_length(p_token)<24 or char_length(p_token)>256 then return null; end if;
  select * into v_inv from public.invitations where token_hash=encode(extensions.digest(p_token,'sha256'),'hex') and status='active' and (expires_at is null or expires_at>now()) limit 1;
  if not found then return null; end if;
  select * into v_event from public.events where id=v_inv.event_id and status='published'; if not found then return null; end if;
  if v_inv.guest_id is not null then select * into v_guest from public.guests where id=v_inv.guest_id; end if;
  select * into v_rsvp from public.rsvps where invitation_id=v_inv.id;
  update public.invitations set first_opened_at=coalesce(first_opened_at,now()),last_opened_at=now(),open_count=open_count+1 where id=v_inv.id;
  insert into public.event_analytics(event_id,invitation_id,event_name,locale) values(v_event.id,v_inv.id,'invite_open',coalesce(v_guest.locale,v_event.locale_default));
  return jsonb_build_object(
    'event',jsonb_build_object('slug',v_event.slug,'type',v_event.event_type,'title',v_event.title,'subtitle',v_event.subtitle,'timezone',v_event.timezone,'startsAt',v_event.starts_at,'endsAt',v_event.ends_at,'rsvpOpensAt',v_event.rsvp_opens_at,'rsvpClosesAt',v_event.rsvp_closes_at,'config',v_event.config),
    'guest',case when v_guest.id is null then null else jsonb_build_object('displayName',v_guest.display_name,'locale',v_guest.locale) end,
    'invitation',jsonb_build_object('maxGuests',v_inv.max_guests,'status',v_inv.status),
    'rsvp',case when v_rsvp.id is null then null else jsonb_build_object('attendance',v_rsvp.attendance,'guestCount',v_rsvp.guest_count,'message',v_rsvp.message,'respondedAt',v_rsvp.responded_at) end);
end; $$;

create or replace function public.submit_invitation_rsvp(p_token text,p_attendance text,p_guest_count integer default 1,p_message text default null,p_locale text default 'ar')
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_inv public.invitations%rowtype; v_event public.events%rowtype; v_rsvp_id uuid; v_pass_token text; v_pass_id uuid;
begin
  if p_token is null or char_length(p_token)<24 or char_length(p_token)>256 then raise exception 'invalid_invitation'; end if;
  if p_attendance not in ('attending','declining') then raise exception 'invalid_attendance'; end if;
  if p_locale not in ('ar','en') then p_locale:='ar'; end if;
  if p_message is not null and char_length(p_message)>1000 then raise exception 'message_too_long'; end if;
  select * into v_inv from public.invitations where token_hash=encode(extensions.digest(p_token,'sha256'),'hex') and status='active' and (expires_at is null or expires_at>now()) limit 1 for update;
  if not found then raise exception 'invalid_invitation'; end if;
  select * into v_event from public.events where id=v_inv.event_id and status='published'; if not found then raise exception 'event_unavailable'; end if;
  if v_event.rsvp_opens_at is not null and now()<v_event.rsvp_opens_at then raise exception 'rsvp_not_open'; end if;
  if v_event.rsvp_closes_at is not null and now()>v_event.rsvp_closes_at then raise exception 'rsvp_closed'; end if;
  if p_attendance='declining' then p_guest_count:=1; end if;
  if p_guest_count<1 or p_guest_count>v_inv.max_guests then raise exception 'guest_count_exceeded'; end if;
  insert into public.rsvps(event_id,invitation_id,attendance,guest_count,message,locale)
  values(v_event.id,v_inv.id,p_attendance,p_guest_count,nullif(btrim(p_message),''),p_locale)
  on conflict(invitation_id) do update set attendance=excluded.attendance,guest_count=excluded.guest_count,message=excluded.message,locale=excluded.locale,responded_at=now()
  returning id into v_rsvp_id;
  update public.guest_passes set status='revoked',revoked_at=now() where invitation_id=v_inv.id and status='active';
  if p_attendance='attending' then
    v_pass_token:=replace(gen_random_uuid()::text,'-','')||replace(gen_random_uuid()::text,'-','');
    insert into public.guest_passes(event_id,invitation_id,pass_hash,pass_hint)
    values(v_event.id,v_inv.id,encode(extensions.digest(v_pass_token,'sha256'),'hex'),right(v_pass_token,8)) returning id into v_pass_id;
    insert into public.event_analytics(event_id,invitation_id,event_name,locale) values(v_event.id,v_inv.id,'pass_issue',p_locale);
  end if;
  insert into public.event_analytics(event_id,invitation_id,event_name,locale,properties)
  values(v_event.id,v_inv.id,'rsvp_submit',p_locale,jsonb_build_object('attendance',p_attendance,'guestCount',p_guest_count));
  return jsonb_build_object('ok',true,'rsvpId',v_rsvp_id,'attendance',p_attendance,'guestCount',p_guest_count,'passToken',v_pass_token,'passId',v_pass_id);
end; $$;

create or replace function public.track_invitation_event(p_token text,p_event_name text,p_locale text default null,p_properties jsonb default '{}'::jsonb)
returns boolean language plpgsql security definer set search_path=public,pg_temp as $$
declare v_inv public.invitations%rowtype;
begin
  if p_event_name not in ('share','map_open','calendar_add','language_change') then return false; end if;
  if p_token is null or char_length(p_token)<24 or char_length(p_token)>256 then return false; end if;
  if octet_length(coalesce(p_properties,'{}'::jsonb)::text)>2048 then p_properties:='{}'::jsonb; end if;
  select * into v_inv from public.invitations where token_hash=encode(extensions.digest(p_token,'sha256'),'hex') and status='active' and (expires_at is null or expires_at>now()) limit 1;
  if not found then return false; end if;
  insert into public.event_analytics(event_id,invitation_id,event_name,locale,properties)
  values(v_inv.event_id,v_inv.id,p_event_name,case when p_locale in ('ar','en') then p_locale else null end,coalesce(p_properties,'{}'::jsonb));
  return true;
end; $$;

revoke all on function public.get_public_event(text) from public;
revoke all on function public.resolve_invitation(text) from public;
revoke all on function public.submit_invitation_rsvp(text,text,integer,text,text) from public;
revoke all on function public.track_invitation_event(text,text,text,jsonb) from public;
grant execute on function public.get_public_event(text) to anon,authenticated;
grant execute on function public.resolve_invitation(text) to anon,authenticated;
grant execute on function public.submit_invitation_rsvp(text,text,integer,text,text) to anon,authenticated;
grant execute on function public.track_invitation_event(text,text,text,jsonb) to anon,authenticated;

insert into public.events(slug,event_type,title,subtitle,timezone,starts_at,ends_at,rsvp_opens_at,rsvp_closes_at,status,locale_default,config)
values('mostafa-amira-2026','wedding','Mostafa & Amira','Operation Forever','Africa/Cairo','2026-07-31 19:00:00+03','2026-07-31 23:00:00+03','2026-06-01 00:00:00+03','2026-07-31 18:30:00+03','published','ar',jsonb_build_object('venue',jsonb_build_object('name','Dar Al Eshara','area','Almazah','city','Cairo','mapsUrl','https://maps.app.goo.gl/BzxKEpQVtUCoLMjm7?g_st=afm'),'theme','emerald-editorial','languages',jsonb_build_array('ar','en')))
on conflict(slug) do update set event_type=excluded.event_type,title=excluded.title,subtitle=excluded.subtitle,timezone=excluded.timezone,starts_at=excluded.starts_at,ends_at=excluded.ends_at,rsvp_opens_at=excluded.rsvp_opens_at,rsvp_closes_at=excluded.rsvp_closes_at,status=excluded.status,locale_default=excluded.locale_default,config=excluded.config;
